stored cards feature
Cashflows/cashflows-clientlib-js pull request #13
Opened 2023-11-01 13:17 UTC by bobcashflows

2023-11-03 10:09 UTC, kevinbroeren requested changes
Can we start using the new preparation request endpoint of the payment page, as part of this release?

https://gateway.cashflows.com/**payment/preparation**/{preparationId} => https://gateway.cashflows.com/**preparations**/{preparationId}

2023-11-03 10:09 UTC, kevinbroeren commented on src/cashflows.js
> +const CASHFLOWS_INTEGRATION_ENDPOINT = 'https://gateway-devf.cashflows.com/';
I think this was changed on accident.

2023-11-03 10:09 UTC, kevinbroeren commented on src/cashflows.js
> +	// Use the default template to render the card list items. This can be overriden.
overrid**d**en :)

2023-11-03 10:09 UTC, kevinbroeren commented on src/img/bin.png
Is this picture copyright free and are we allowed to redistribute it?

2023-11-03 10:09 UTC, kevinbroeren commented on test/mocha.setup.js
> +			return [ 200, { data: [ { maskedCardNumber: '**** **** **** 1234', cardExpiryMonth: 1, cardExpiryYear: 23, encryptedCardData: 'AAAA' } ] } ];
The masked card number does not follow industry standard masking (0000 00** **** 0000)

2023-11-23 10:28 UTC, bobcashflows commented
The new endpoints will be used with this PR: https://github.com/Cashflows/cashflows-clientlib-js/pull/15

2023-11-23 11:11 UTC, kevinbroeren approved these changes

2024-01-03 09:41 UTC, merged